// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvc-GRfzX2oVqsmTaTwRkZf2d3ufO34mo',
    appId: '1:25308758765:web:ebf6a3c1a16db06d3f42e4',
    messagingSenderId: '25308758765',
    projectId: 'olx-clone-faba7',
    authDomain: 'olx-clone-faba7.firebaseapp.com',
    storageBucket: 'olx-clone-faba7.appspot.com',
    measurementId: 'G-26L748KS3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsP1t7TXLwnHQO-w_O6eGVMt0OUJVOthk',
    appId: '1:25308758765:android:3367e02323b451fe3f42e4',
    messagingSenderId: '25308758765',
    projectId: 'olx-clone-faba7',
    storageBucket: 'olx-clone-faba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Kvyp9T70xIZXDq_rYqQsh4UoyZTxHgM',
    appId: '1:25308758765:ios:81146665e68203b73f42e4',
    messagingSenderId: '25308758765',
    projectId: 'olx-clone-faba7',
    storageBucket: 'olx-clone-faba7.appspot.com',
    androidClientId: '25308758765-m93413kidm0vv7lqjv20r4ta9nst55uf.apps.googleusercontent.com',
    iosClientId: '25308758765-03hitnaoeldn4omp99eh6h6j0pk6onr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxClone1',
  );
}
